import path from 'path';

export interface LicensePayload {
    customerName: string;
    type: 'COMMUNITY' | 'STARTER' | 'PRO' | 'ENTERPRISE';
    maxProductLines: number;
    maxUsers?: number;
    expiresAt: string;
}

export interface VerificationResult {
    valid: boolean;
    claims?: LicensePayload;
    error?: string;
}

declare const __non_webpack_require__: any;

// Cache the loaded module
let wasmModule: any = null;

export function verifyLicenseWithWasm(token: string): VerificationResult {
    if (!wasmModule) {
        try {
            // Resolve path to the pkg directory generated by wasm-pack
            // In a standard Next.js server runtime, process.cwd() is the project root.
            const pkgPath = path.join(process.cwd(), 'native/license-verifier/pkg/license_verifier.js');


            // Use eval('require') or similar to bypass Webpack/Turbopack static analysis 
            // since we want runtime resolution from filesystem.
            const dynamicRequire = typeof __non_webpack_require__ !== 'undefined' ? __non_webpack_require__ : require;
            wasmModule = dynamicRequire(pkgPath);

            // console.log('[LicenseWASM] Module loaded successfully.');
        } catch (e) {
            console.error('[LicenseWASM] Failed to load WASM module:', e);
            console.error('[LicenseWASM] CWD:', process.cwd());
            console.error('[LicenseWASM] __dirname:', __dirname);
            const pkgPath = path.join(process.cwd(), 'native/license-verifier/pkg/license_verifier.js');
            console.error('[LicenseWASM] Target Path:', pkgPath);
            try {
                 
                const fs = require('fs');
                console.error('[LicenseWASM] File Exists?', fs.existsSync(pkgPath));

                // Print contents of nested dirs to help debug
                const nativeDir = path.join(process.cwd(), 'native');
                if (fs.existsSync(nativeDir)) {
                    console.error('[LicenseWASM] /app/native contents:', fs.readdirSync(nativeDir));
                    const pkgDir = path.join(nativeDir, 'license-verifier/pkg');
                    if (fs.existsSync(pkgDir)) {
                        console.error('[LicenseWASM] /app/native/license-verifier/pkg contents:', fs.readdirSync(pkgDir));
                    } else {
                        console.error('[LicenseWASM] /app/native/license-verifier/pkg DOES NOT EXIST');
                    }
                } else {
                    console.error('[LicenseWASM] /app/native DOES NOT EXIST');
                }

            } catch (err) {
                console.error('[LicenseWASM] Debugging FS failed:', err);
            }

            // Fallback or critical failure? 
            // If the module is missing, we can't secure verification.
            return {
                valid: false,
                error: 'Security module missing. Please ensure native/license-verifier is built.'
            };
        }
    }

    try {
        // call verify_license form Rust
        const result = wasmModule.verify_license(token);
        return result as VerificationResult;
    } catch (e) {
        console.error('[LicenseWASM] Error during verification execution:', e);
        return { valid: false, error: 'Verification runtime error.' };
    }
}
